### ISSUE TITLE
Can't update to latest version of Unity - textures and scripts all missing

### ISSUE THREAD

**Issue by MishManners** [maxilevi/project-skylines#29]
Having trouble opening and building this game with the latest version of Unity.

Is there a way to easily see what assets go to what scripts?
Also the textures for the ship and material is missing (meaning there is no ship and no terrain in the scene).
Collision script also not working.

Any help/updates on this would be awesome.

Check out the issues we were having here: (yes we live streamed the whole thing!)
https://www.twitch.tv/videos/900068261

**Comment by maxilevi** [comment]
Oh, that must have ruined the stream, I am sorry.

I am a bit busy now but I will try to clone it in the weekend and see if I can find the issues. Will let you know.

Can you tell me your exact version of unity?

**Comment by MishManners** [comment]
Hahah it's okay @maxilevi. We still had a good stream!
The exact version of Unity I'm using is: 2020.1.13f1

Hope that helps.

**Comment by MishManners** [comment]
@maxilevi any update on this?

**Comment by maxilevi** [comment]
> @maxilevi any update on this?

I tried out importing it to Unity 2019. I added a shader that was missing but the rest of the game was working fine. Let me know if it works now

**Comment by MishManners** [comment]
Yeah like I said, nothing worked for us. No one from my stream was able to get it working at all. Is there a readme, or steps we can follow do try it again?

**Comment by maxilevi** [comment]
No, it should work straight out of the box. Did you try it with the latest version?
