### ISSUE TITLE
Main ship does not show up when building in Unity 2019.4.17f1

### ISSUE THREAD

**Issue by pgiokaris** [maxilevi/project-skylines#30]
Hi there Max,

Playing / building the game in Unity 2019.4.17f1 does not include the ship. I have installed Blender 2.92.0 (latest as of today) then did a clean open of the project. The .blend file does show up but it still does not get instantiated when playing the game.

Here is a picture of what a clean project install and starting Game.scene in editor mode looks like:
![Capture](https://user-images.githubusercontent.com/84603320/119204689-ef4bca80-ba4a-11eb-9328-c19301f17143.JPG)

As you can see, the trails are showing up but the ship is not. 

This is a fantastic project and I would be happy to support you in getting the project to compile and work (specifically in exclusive full-screen mode for the above Unity version).

**Comment by pgiokaris** [comment]
Was able to fix by adding .blend files into Player prefab (collision and visual mesh). All works now.

**Comment by mishmanners** [comment]
I'd be keen to hear @pgiokaris how you got this all setup in Unity. Mine still isn't showing up. Thanks in advanced.
